### ISSUE TITLE
Homebrew reporting warning on `brew upgrade`

### ISSUE THREAD

**Issue by eksoparty** [universal-ctags/homebrew-universal-ctags#13]
Warning: Calling 'depends_on :automake' is deprecated!
Use 'depends_on "automake"' instead.
/usr/local/Library/Taps/universal-ctags/homebrew-universal-ctags/universal-ctags.rb:5:in `class:UniversalCtags'
Please report this to the universal-ctags/universal-ctags tap!

**Comment by mikedfunk** [comment]
+1

**Comment by lucafavatella** [comment]
@xitkov I believe that PR #8 - merged 9 days ago - fixed this. May I suggest you re-test with a fresh version of the formula/tap and update this ticket?

**Comment by eksoparty** [comment]
I had to do `brew untap universal-ctags/universal-ctags` and then `brew tap universal-ctags/universal-ctags` to fix it.

Is there a way to update the tap without re-tapping?

**Comment by cweagans** [comment]
You should be able to `brew update` to get the latest formula. Did that not work?

**Comment by eksoparty** [comment]
No, it did not work.

**Comment by thoughton** [comment]
~~I may be wrong, but I think it's `brew upgrade` to make sure installed formulas are the latest.~~

Ah, please ignore me. I've just re-read the original issue and realised my comment was not helpful at all. Sorry!

**Comment by KazuakiM** [comment]
Why is it open though the problem is solved?
