### ISSUE TITLE
"repetition-operator operand invalid" warning when run with no options.

### ISSUE THREAD

**Issue by thoughton** [universal-ctags/homebrew-universal-ctags#18]
Running with no extra command line options gives me the following warning:
```
$ ctags
ctags: Warning: regcomp ^[ 	]*+([A-Za-z0-9_]+)(;|\([^)]*:[^)]*\)): repetition-operator operand invalid
```
Is this anything to worry about?

I'm installed from HEAD and up-to-date:
```
$ brew info universal-ctags
.../homebrew/Cellar/universal-ctags/HEAD-e1dcb48 (7 files, 629.7K) *
  Built from source on 2016-12-29 at 21:37:06
```

I'm running on Mac OS X 10.9.5.

Thanks!

**Comment by KazuakiM** [comment]
I think it's a matter of setting.
You use empty ```~/.ctags``` and try to solve the error.

**Comment by thoughton** [comment]
You're right, I had a `~/.ctags` file, likely from an old (not "universal-") version of ctags, just containing some `Haxe` language definitions. I no longer need those definitions, and deleting that file solved the problem.

Thanks for the help!

**Comment by masatake** [comment]
(I will make ctags load ~/.u-ctags instead of ~/.ctags.)
