### ISSUE TITLE
Change description homebrew repo

### ISSUE THREAD

**Issue by ffes** [universal-ctags/homebrew-universal-ctags#2]
I suggest to change the description of this repo to something like

"Mac OSX Homebrew Tap"
or
"OSX Homebrew Tap for Universal Ctags"
or
"Homebrew Tap for Universal Ctags on OSX"

This way it is clear when you look at https://github.com/universal-ctags/ what this repo is all about, especially for non OSX users who haven't got a clue what Homebrew is.

**Comment by cweagans** [comment]
Done.
