### ISSUE TITLE
I have some warnings after the installation is complete, do not know how to do

### ISSUE THREAD

**Issue by liulipeng** [universal-ctags/homebrew-universal-ctags#21]
ctags: Warning: Don't reuse the kind letter `f' in a language Ruby (old: "method", new: "function")

ctags: Warning: Don't reuse the kind letter `f' in a language Ruby (old: "method", new: "function")

ctags: Warning: Don't reuse the kind letter `f' in a language Ruby (old: "method", new: "function")

ctags: Warning: Don't reuse the kind letter `f' in a language Ruby (old: "method", new: "function")

ctags: Warning: Don't reuse the kind letter `f' in a language Ruby (old: "method", new: "function")

ctags: Warning: Don't reuse the kind letter `f' in a language Ruby (old: "method", new: "function")

ctags: Warning: Don't reuse the kind letter `h' in a language markdown (old: "heading1", new: "heading2")

ctags: Warning: Don't reuse the kind letter `h' in a language markdown (old: "heading1", new: "heading3")

ctags: Warning: Language "css" already defined

**Comment by KazuakiM** [comment]
I think it's a matter of setting.
You use empty ```~/.ctags``` and try to solve the error.
If there is no problem with installation, please ask this head owner.
