### ISSUE TITLE
brew install fails to link libxml2

### ISSUE THREAD

**Issue by tplunket** [universal-ctags/homebrew-universal-ctags#30]
I don't know a lot about Mac dev unfortunately but like some other open issues, the Homebrew instructions complete with a failure. I tried the workaround mentioned elsewhere regarding just building from the source cache but that fails in the same way...

In my case, it's failing to link. In the output there's a bunch of CC calls, then `CCLD ctags` then I get a list of undefined symbols; `_xmlDocGetRootElement`, `_xmlFree`, and so on. `/usr/lib` has a 'libxml2.dylib' and a line in the config.log says:

    checking for libxml-2.0 >= 2.7.7... yes

...although it's a symlink to libxml2.2.dylib.

Not sure what to do at this point short of removing the XML parser.

**Comment by KazuakiM** [comment]
Hi @tplunket ,
It is probably resolved by installing libxml2 with homebrew. However, I thought that this problem was strange in the past. I think that `autoconf` is misunderstanding.

By the way, will the result of the following command still be 2.2?
```
$ /usr/bin/xml2-config --version
```

**Comment by KazuakiM** [comment]
Hi @tplunket ,
I have an additional question.Which OS do you use?
It may be dependent on the OS.

There were other modifications that seemed to be similar.
* https://github.com/Homebrew/homebrew-core/blob/66b1e4307a993db80437046071acff88ba18e037/Formula/libxmlsec1.rb#L15
* https://github.com/Homebrew/homebrew-core/blob/f72b0fc7e24199779a0e419936d5834e11808eee/Formula/spdylay.rb#L21
* https://github.com/Homebrew/homebrew-core/blob/57a4a5104f858cb40284f4f4286a79f2d1c815d4/Formula/cfengine.rb#L14

**Comment by tplunket** [comment]
@KazuakiM /usr/bin/xml2-config reports 2.9.2. /usr/local/bin/xml2-config reports 2.7.7 and that's the one that's found by `which xml2-config`. I honestly couldn't say where that came from.

**Comment by KazuakiM** [comment]
Hi @tplunket 
I update this project , add "--without-xml" options.
So add options and try again?

**Comment by smwyzi** [comment]
if u don't need xml feature, just use:
` ./configure --prefix=/usr/local --disable-xml`
