### ISSUE TITLE
How to brew global with universal-ctags?

### ISSUE THREAD

**Issue by hisnawi** [universal-ctags/homebrew-universal-ctags#32]
When I try this:

```
❯ brew install global --with-universal-ctags=/usr/local/bin/ctags
Warning: global: this formula has no --with-universal-ctags= option so it will be ignored!

```
How to achieve that using brew?

**Comment by cweagans** [comment]
This is not a universal-ctags issue. Please file an issue in the homebrew-core repository where the [global formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/global.rb) is maintained.
