### ISSUE TITLE
Should python be a dependency rather than using the system python?

### ISSUE THREAD

**Issue by nerdrew** [universal-ctags/homebrew-universal-ctags#43]
It looks like universal-ctags requires python + setuptools to install. Rather than use the system python, should the formula depend on the homebrew python@2?

**Comment by nerdrew** [comment]
Hmm. I had a number of other issues as well. Maybe this should just get closed.

FWIW to get it to install on linuxbrew I did:

```
brew install universal-ctags/universal-ctags/universal-ctags --HEAD --env=std
```

and I had to install python-docutils, not python3-docutils.

**Comment by KazuakiM** [comment]
@nerdrew 
Hi, Sorry for replying so late.
I update PR #45 now. One more time, please.
