### ISSUE TITLE
Remove python3 dependency

### ISSUE THREAD

**Issue by wookayin** [universal-ctags/homebrew-universal-ctags#48]
I don't think it makes much sense to have python3 as a dependency (#43, #45). I want to keep the brew python version as I already have, but the current brew formula would always require me to update to new version whenever installing.

Do you think it would be possible to get rid of python3 or docutils dependency, allowing users to just use existing python installation? Or we should be able to optionally install it without python dependency.

**Comment by wookayin** [comment]
Workaround: If one already have `docutils` installed, we can ignore dependencies like: 

```
brew install --HEAD universal-ctags/universal-ctags/universal-ctags --ignore-dependencies
```

**Comment by KazuakiM** [comment]
Hi @wookayin 
I update fomula changes `:build` to `:recommended` .
So Add `--without-docutils` options.
Can you do it again?

**Comment by wookayin** [comment]
```
brew install --HEAD --without-docutils universal-ctags/universal-ctags/universal-ctags
```

Yes, this works for me. Thank you for making it optional!
