### ISSUE TITLE
error: possibly undefined macro: AM_INIT_AUTOMAKE

### ISSUE THREAD

**Issue by thtb** [universal-ctags/homebrew-universal-ctags#5]
occur error: possibly undefined macro: AM_INIT_AUTOMAKE

but i reinstall the automake and still doesn't work

here's the log https://gist.github.com/755ba53de9e734215a17

**Comment by thtb** [comment]
https://gist.github.com/35a84e6154647c3daad3
new log after update and fix slash problem

**Comment by bruschill** [comment]
I'm having this issue as well. Any luck figuring it out?

**Comment by choco** [comment]
Check pending pull request

**Comment by thtb** [comment]
what can do now,  can i change brew to check you branch instead the master

**Comment by choco** [comment]
Yes you can use my branch in the mean time:
Tap my fork:

```
brew untap cHoco/universal-ctags
```

And finally:

```
brew install cHoco/universal-ctags
```

**Comment by zbeekman** [comment]
It looks like #6 fixed this issue, no?

Can anyone confirm that is been resolved?

**Comment by KazuakiM** [comment]
The problem is now solved. Thank you for your help.
