### ISSUE TITLE
Move from HEAD to releases

### ISSUE THREAD

**Issue by jandamm** [universal-ctags/homebrew-universal-ctags#58]
Recently universal-ctags added weekly releases: https://github.com/universal-ctags/ctags/issues/1038#issuecomment-706654032

Is it possible to update the tap to use the release version (when `--HEAD` is not specified).
Would make it easier to integrate with `brew bundle`, since this does not update `--HEAD` formulas.

**Comment by equal-l2** [comment]
This will also allow us to build a bottle (pre-built binary for Homebrew) using GitHub Actions!

**Comment by KazuakiM** [comment]
Fixed : https://github.com/Homebrew/homebrew-core/pull/78026
